---
title: "Visualizing Soccer Data"
description: "Exploring Argentina vs. Saudi Arabia match via Data viz using Python "
date: "2026-05-25"
categories: [Python, EDA, Soccer, Data, Visualization, StatsBomb]
format:
  html:
    code-fold: true    
    code-tools: true
jupyter: python3
---

## Overview

I had used R, ggplot2, ggsoccer and other R packages to build visualizations for my <a href = 
"https://tripps44.github.io/projects/posts/worldcup2022-argentina/" target="_blank"> 2022 world cup microsite showcasing Argentina's progress </a>
In this blog post, I'm using Python to explore building a few different set of visualizations for the Argentina vs. Saudi Arabia game

## Tools Used

- **Languages:** Python
- **IDE:** Positron
- **Packages:** quarto, pandas, numpy, mplsoccer, adjustText

## Python Imports

```{python}

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from mplsoccer import Pitch, VerticalPitch, Sbopen 
import pandas as pd
import numpy as np
from adjustText import adjust_text


```

## Finding the match id's for Argentina's games
```{python}
# https://mplsoccer.readthedocs.io/en/latest/gallery/statsbomb/plot_statsbomb_data.html#match-data
parser = Sbopen()

# 2022 World Cup
matches = parser.match(competition_id=43, season_id=106)

TEAM = "Argentina"

team_matches = matches[
    (matches['home_team_name'] == TEAM) | 
    (matches['away_team_name'] == TEAM)
]

print(team_matches[['match_id', 'home_team_name', 
                     'away_team_name', 'match_date']].to_string())
```
Match id 3857300 is for the specific game: Argentina vs Saudi Arabia

## Loading the dataframes
```{python}
# Load match events
# https://mplsoccer.readthedocs.io/en/latest/gallery/statsbomb/plot_statsbomb_data.html#event-data

events, related, freeze, tactics = parser.event(3857300)

# Argentina passes
arg_passes = events[
    (events['type_name'] == 'Pass') & 
    (events['team_name'] == 'Argentina')
]

# Saudi Arabia passes
ksa_passes = events[
    (events['type_name'] == 'Pass') & 
    (events['team_name'] == 'Saudi Arabia')
]

# Argentina shots
arg_shots = events[
    (events['type_name'] == 'Shot') & 
    (events['sub_type_name'] !='Penalty') &
    (events['team_name'] == 'Argentina')
]

# Saudi Arabia shots
ksa_shots = events[
    (events['type_name'] == 'Shot') & 
    (events['sub_type_name'] !='Penalty') &
    (events['team_name'] == 'Saudi Arabia')
]

print(f"Argentina passes: {len(arg_passes)}, shots: {len(arg_shots)}")
print(f"Saudi Arabia passes: {len(ksa_passes)}, shots: {len(ksa_shots)}")
print("* excluding penalties")
```


## Function setup 
```{python}
def get_pre_shot_passes(passes_df, shots_df):
    """Get passes made within 15 seconds of a shot"""

    pre_shot = [] # empty list to collect results

    for _, shot in shots_df.iterrows():
        #looping through every shot one at a time

        shot_time = shot['minute'] * 60 + shot['second']
        # converting shot time to total seconds

        window = passes_df[
            (passes_df['minute'] * 60 + passes_df['second'])
            .between(shot_time - 15, shot_time)
        
        #convert every pass time to total seconds
        # then find passes that happened within the 15 second window BEFORE the shot
        ]
        pre_shot.append(window)
        # add to results list

    return pd.concat(pre_shot).drop_duplicates() if pre_shot else pd.DataFrame()
        # combine all results
        # remove duplicates
        # return empty dataframe if nothing is found 

arg_pre_shot = get_pre_shot_passes(arg_passes, arg_shots)
ksa_pre_shot = get_pre_shot_passes(ksa_passes, ksa_shots)


```

## 1. Pass Map Viz - Buildup to the Shot

```{python}
fig, axes = plt.subplots(1, 2, figsize=(16, 8))
fig.patch.set_facecolor('#ffffff')
fig.suptitle('Pass Buildup to Shot (Within 15 Seconds)',
             color='black', fontsize=22, y=1.04, fontweight = 'bold')

for ax, passes_df, team, color in zip(
    axes,
    [arg_pre_shot, ksa_pre_shot],
    ["Argentina", "Saudi Arabia"],
    ['#75AADB', '#00b100']
):
    pitch = Pitch(
        pitch_type='statsbomb',
        pitch_color='#fafafa',
        line_color='#cccccc',
        line_zorder=2
    )
    pitch.draw(ax=ax)

    # complete passes
    complete = passes_df[passes_df['outcome_name'].isna()]
    if not complete.empty:
        pitch.arrows(
            complete.x, complete.y,
            complete.end_x, complete.end_y,
            ax=ax,
            color=color,
            width=2,
            headwidth=4,
            alpha=0.8,
            label='Complete'
        )

    # incomplete passes
    incomplete = passes_df[passes_df['outcome_name'].notna()]
    if not incomplete.empty:
        pitch.arrows(
            incomplete.x, incomplete.y,
            incomplete.end_x, incomplete.end_y,
            ax=ax,
            color='#000000',
            width=1.5,
            headwidth=3,
            alpha=0.9,
            label='Incomplete'
        )

    ax.set_title(team, color='black', fontsize=13, pad=10)
    ax.legend(facecolor='#fafafa', labelcolor='black',
              loc='upper left', fontsize=13,
              markerscale=1.5,
              framealpha=0.8
              )

plt.tight_layout()
plt.savefig('images/pass_map.png', dpi=150,
            bbox_inches='tight', facecolor='#fafafa')
plt.show()
```
Why Track passes 15 seconds before a shot?

This type of tracking reveals the precise off ball movements, spacing and
defensive fractures that create scoring opportunities, rather than just 
analyzing the final action. If the coach only looks at shots, then they're
reacting only to the outcome. Looking at passes 15 seconds before a shot 
can give an idea of spatial patterns before looking at the shot map

🟦 Argentina Takeaways

1. The high volume of passes show that Argentina dominated possession
2. Short and quick arrows are clustered together meaning a lot of tight passing was carried out
3. Argentina controlled the ball and recycled possession heavily in the opponent's half 
creating a sustained attacking pressure

🟩 Saudi Takeways

Saudi Arabia sat deeper, played fewer passes and relied on direct balls when they played forward

## 2. Shot Map

```{python}
fig, axes = plt.subplots(1,2,  figsize=(16, 8))
fig.patch.set_facecolor('#ffffff')
fig.suptitle('Shot Map',
             color='black', fontsize=22, y=1.05, fontweight = 'bold')

# subtitle
fig.text(0.5, 1.00,
    'Circle size proportional to xG value',
    color='#aaaaaa', fontsize=11,
    ha='center', va='top')

for ax, shots_df, team, color in zip(
    axes,
    [arg_shots, ksa_shots],
    ["Argentina", "Saudi Arabia"],
    ['#75AADB', '#00b100']
):
    pitch = Pitch(
        pitch_type='statsbomb',
        pitch_color='#fafafa',
        line_color='#cccccc',
        half=True
    )
    pitch.draw(ax=ax)

    # Goals
    goals = shots_df[shots_df['outcome_name'] == 'Goal']
    if not goals.empty:
        pitch.scatter(
            goals.x, goals.y,
            s=goals.shot_statsbomb_xg * 1000,
            c='#9b00b1',
            edgecolors='white',
            linewidth=0.8,
            ax=ax,
            zorder=3,
            label='Goal'
        )

    # Non goals
    non_goals = shots_df[shots_df['outcome_name'] != 'Goal']
    if not non_goals.empty:
        pitch.scatter(
            non_goals.x, non_goals.y,
            s=non_goals.shot_statsbomb_xg * 1000,
            c=color,
            edgecolors='white',
            linewidth=0.8,
            alpha=0.6,
            ax=ax,
            zorder=2,
            label='No Goal'
        )
    

    ax.set_title(team, color='black', fontsize=13, pad=10)
    ax.legend(facecolor='#fafafa', labelcolor='black',
              loc='upper left', fontsize=13,
              markerscale=1.5,
              framealpha=0.8
              )

plt.tight_layout()
plt.savefig('images/shot_map.png', dpi=150,
            bbox_inches='tight', facecolor='#fafafa')
plt.show()
```

Argentina dominated territorially with 14 shots (excluding the 1 penalty taken by Messi) but Saudi Arabia's 
disciplined defensive block restricted clear chances. 

Saudi Arabia took 3 shots to score twice 


## 3. Passing Networks


```{python}
# Argentina top 5
arg_top5 = arg_passes[
    arg_passes['outcome_name'].isna()
].groupby('player_name').size()\
 .reset_index(name='total_passes')\
 .sort_values('total_passes', ascending=False)\
 .head(5)

print("Argentina Top 5:")
print(arg_top5.to_string())

# Saudi Arabia top 5
ksa_top5 = ksa_passes[
    ksa_passes['outcome_name'].isna()
].groupby('player_name').size()\
 .reset_index(name='total_passes')\
 .sort_values('total_passes', ascending=False)\
 .head(5)

print("\nSaudi Arabia Top 5:")
print(ksa_top5.to_string())
```

```{python}
def draw_passing_network(ax, passes_df, team, color, top5):
    """Passing network for top 5 players"""
    
    # passes between top 5 players only
    complete = passes_df[
        passes_df['outcome_name'].isna() &
        passes_df['pass_recipient_name'].notna() &
        passes_df['player_name'].isin(top5) &
        passes_df['pass_recipient_name'].isin(top5)
    ]

    # pass pairs
    pairs = complete.groupby(
        ['player_name', 'pass_recipient_name']
    ).size().reset_index(name='pass_count')

    # average positions
    avg_pos = complete.groupby('player_name').agg(
        avg_x=('x', 'mean'),
        avg_y=('y', 'mean'),
        total=('x', 'count')
    ).reset_index()

    pitch = Pitch(
        pitch_type='statsbomb',
        pitch_color='#fafafa',
        line_color='#cccccc'
    )
    pitch.draw(ax=ax)

    # draw lines
    for _, row in pairs.iterrows():
        p1 = avg_pos[avg_pos['player_name'] == row['player_name']]
        p2 = avg_pos[avg_pos['player_name'] == row['pass_recipient_name']]
        if not p1.empty and not p2.empty:
            pitch.lines(
                p1.avg_x.values[0], p1.avg_y.values[0],
                p2.avg_x.values[0], p2.avg_y.values[0],
                ax=ax,
                lw=row['pass_count'] * 0.4,
                color=color,
                alpha=0.5,
                zorder=1
            )

    # draw nodes
    pitch.scatter(
        avg_pos.avg_x, avg_pos.avg_y,
        s=avg_pos.total * 8,
        c=color,
        edgecolors='white',
        linewidth=1,
        ax=ax,
        zorder=3
    )

    # last name only
    texts = []
    for _, row in avg_pos.iterrows():
        last_name = row['player_name'].split()[-1]
        txt = ax.text(
            row['avg_x'], row['avg_y'],
            last_name,
            color='black',
            fontsize=10,
            fontweight='bold',
            ha='center',
            va='bottom',
            zorder=5
        )
        texts.append(txt)

    # adjustText: avoids label overlap
    # similar to ggrepel 
    adjust_text(
        texts,
        ax=ax,
        expand=(1.2, 1.4),
        arrowprops=dict(
            arrowstyle='-',
            color='#999999',
            lw=0.5
        )
    )

    ax.set_title(team, color='black',
                 fontsize=12, pad=12)
    return ax


# top 5 player lists
arg_top5_list = arg_top5['player_name'].tolist()
ksa_top5_list = ksa_top5['player_name'].tolist()

fig, axes = plt.subplots(2, 1, figsize=(16, 8))
fig.patch.set_facecolor('#fafafa')
fig.suptitle('Top 5 Passers',
             color='black', fontsize=22,
             fontweight='bold', y=1.04)
fig.text(
    0.5, 1.00,
    'Node size = total passes \n Line width = pass frequency',
    color='#666666', fontsize=10,
    fontstyle='italic', ha='center', va='top'
)

for ax, passes_df, team, color, top5 in zip(
    axes,
    [arg_passes, ksa_passes],
    ["Argentina", "Saudi Arabia"],
    ['#75AADB', '#00b100'],
    [arg_top5_list, ksa_top5_list]   
):
    draw_passing_network(ax, passes_df, team, color, top5)

plt.tight_layout()
plt.savefig('images/passing_network.png', dpi=150,
            bbox_inches='tight', facecolor='#fafafa')
plt.show()

```

Argentina's top 5 passers were almost entirely confined to their 
own defensive third, a striking visual that tells the story of 
Saudi Arabia's relentless high press. Otamendi and Romero, both 
center backs, were forced into heavy ball circulation at the back, 
with Paredes and De Paul dropping deep to offer passing options 
rather than driving forward. The tightly clustered network suggests 
Argentina struggled to progress the ball through midfield and build 
attacks from deep (an unusual sight for a team of their quality)

Saudi Arabia's network tells the opposite story. Their top 5 passers 
operated across a wider area of the pitch, with Owais distributing 
from deep while Al-Malki, Kanoo and Hamid formed an active midfield 
triangle in the center of the pitch

## 4. Heatmap 
```{python}
fig, axes = plt.subplots(2, 1, figsize=(14, 10))  
fig.patch.set_facecolor('#fafafa')
fig.suptitle('Touch Heatmaps',
             color='black', fontsize=16,
             fontweight='bold', y=1.02)
fig.text(
    0.5, 0.99,
    'Based on pass locations across the full match',
    color='#666666', fontsize=10,
    fontstyle='italic', ha='center',  va='top'
)

for ax, passes_df, team, cmap in zip(
    axes,
    [arg_passes, ksa_passes],
    ["Argentina", "Saudi Arabia"],
    ['Blues', 'Greens']
):
    pitch = Pitch(
        pitch_type='statsbomb',
        pitch_color='#fafafa',
        line_color='#cccccc'
    )
    

    pitch.kdeplot(
        passes_df.x, passes_df.y,
        ax=ax,
        cmap=cmap,
        fill=True,
        alpha=0.3,
        levels=10,       
        thresh=0.16,     
        bw_adjust=1.2
    )

    pitch.draw(ax=ax)
    
    ax.set_title(team, color='black',
                 fontsize=13, pad=12)

plt.tight_layout()
plt.savefig('images/heatmap.png', dpi=150,
            bbox_inches='tight', facecolor='#fafafa')
plt.show()
```
Argentina's right sided concentration reflects both their natural build up structure through 
De Paul and Paredes and Saudi Arabia's success in forcing Argentina to recycle possession sideways 
in their own half, rather than progress forward.

Saudi Arabia's touches were spread across a much wider central zone, with two distinct hotspots - 
1. Deep right where they absorbed Argentine pressure
2. In the central midfield where they launched their counter attacks. 

The coverage across the full width of their defensive and middle third reflects a well defined 
defensive shape that utilized space effectively

